import json
import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ALLOWED_RESULTS = {
    "results/diagnostic/route_a_degree_matched_v1/summary/summary.json",
    "results/diagnostic/route_a_prospective_v2/analysis/diagnostic_audit.json",
    "results/discriminability/route_a_grid_v1/summary/figure_manifest.json",
    "results/discriminability/route_a_grid_v1/summary/records.csv",
    "results/discriminability/route_a_grid_v1/summary/summary.json",
    "results/discriminability/route_a_grid_v1/summary/validation_figure.pdf",
    "results/discriminability/route_a_grid_v1/summary/validation_figure.png",
}
ACTIVE_SECTIONS = [
    "01_introduction",
    "02_related_work",
    "03_decision_protocol",
    "04_prospective_results",
    "05_edge_intervention",
    "06_fixed_degree_analysis",
    "07_discussion",
    "08_conclusion",
]


class PublicRepositoryTests(unittest.TestCase):
    def test_public_entry_documents_exist(self):
        self.assertTrue((ROOT / "README.md").is_file())
        self.assertTrue((ROOT / "CITATION.cff").is_file())

    def test_internal_and_legacy_surfaces_are_absent(self):
        forbidden = (
            "code",
            "tables",
            "docs/plans",
            "docs/neurocomputing_cover_letter_draft.md",
            "docs/neurocomputing_submission_metadata.md",
            "docs/neurocomputing_rewrite_self_review_2026-08-13.md",
            "docs/route_a_adversarial_review.md",
            "docs/route_a_go_no_go_2026-08-13.md",
            "scripts/build_neurocomputing_submission.py",
            "tests/test_neurocomputing_submission_bundle.py",
        )
        present = []
        for path in forbidden:
            candidate = ROOT / path
            if candidate.is_dir():
                if any(item.is_file() for item in candidate.rglob("*")):
                    present.append(path)
            elif candidate.exists():
                present.append(path)
        self.assertEqual(present, [])

    def test_only_compact_results_are_published(self):
        actual = {
            path.relative_to(ROOT).as_posix()
            for path in (ROOT / "results").rglob("*")
            if path.is_file()
        }
        self.assertEqual(actual, ALLOWED_RESULTS)

    def test_all_published_json_is_valid(self):
        failures = []
        for path in ROOT.rglob("*.json"):
            try:
                json.loads(path.read_text(encoding="utf-8"))
            except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
                failures.append(f"{path.relative_to(ROOT)}: {exc}")
        self.assertEqual(failures, [])

    def test_latex_inputs_resolve(self):
        missing = []
        manuscript = (ROOT / "main_neurocomputing.tex").read_text(encoding="utf-8")
        for target in re.findall(r"\\input\{([^}]+)\}", manuscript):
            if not (ROOT / f"{target}.tex").is_file():
                missing.append(target)
        self.assertEqual(missing, [])

    def test_bibliography_contains_only_cited_entries(self):
        manuscript_paths = [
            ROOT / "main_neurocomputing.tex",
            *sorted((ROOT / "sections").glob("*.tex")),
        ]
        manuscript = "\n".join(
            path.read_text(encoding="utf-8") for path in manuscript_paths
        )
        cited = {
            key.strip()
            for group in re.findall(r"\\cite\w*\{([^}]+)\}", manuscript)
            for key in group.split(",")
        }
        bibliography = (ROOT / "references.bib").read_text(encoding="utf-8")
        published = set(re.findall(r"@\w+\s*\{\s*([^,\s]+)", bibliography))
        self.assertEqual(published, cited)

    def test_manuscript_uses_neutral_ordered_section_names(self):
        manuscript = (ROOT / "main_neurocomputing.tex").read_text(encoding="utf-8")
        actual = re.findall(r"\\input\{sections/([^}]+)\}", manuscript)
        self.assertEqual(actual, ACTIVE_SECTIONS)
        section_files = {
            path.stem for path in (ROOT / "sections").glob("*.tex")
        }
        self.assertEqual(section_files, set(ACTIVE_SECTIONS))

    def test_bounded_ai_declaration_remains_visible(self):
        manuscript = (ROOT / "main_neurocomputing.tex").read_text(encoding="utf-8")
        protocol = (ROOT / "sections" / "03_decision_protocol.tex").read_text(encoding="utf-8")
        self.assertIn("Declaration of generative AI and AI-assisted technologies", manuscript)
        self.assertIn("OpenAI Codex", manuscript)
        self.assertIn("did not generate experimental data or make reporting decisions", protocol)

    def test_no_private_paths_or_informal_process_traces(self):
        forbidden = (
            "d:\\users\\",
            "documents\\毕业论文",
            "based on codex",
            "generated by gemini",
            "for codex:",
            "codex suggested",
            "3-ai review",
            "fsd-gnn",
            "fsd framework",
            "tkde submission",
        )
        hits = []
        this_file = Path(__file__).resolve()
        for suffix in ("*.py", "*.md", "*.tex", "*.json", "*.yml", "*.cff"):
            for path in ROOT.rglob(suffix):
                if path.resolve() == this_file:
                    continue
                text = path.read_text(encoding="utf-8", errors="ignore").lower()
                hits.extend(
                    f"{path.relative_to(ROOT)}: {phrase}"
                    for phrase in forbidden
                    if phrase in text
                )
        self.assertEqual(hits, [])

    def test_readme_states_the_bounded_result_and_verification_path(self):
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        self.assertIn("55.5%", readme)
        self.assertIn("80.9%", readme)
        self.assertIn("91.8%", readme)
        self.assertIn("python -m unittest discover -s tests -v", readme)
        self.assertIn("raw unit-level", readme.lower())

    def test_tests_do_not_hardcode_a_windows_virtualenv(self):
        hits = []
        this_file = Path(__file__).resolve()
        for path in (ROOT / "tests").glob("test_*.py"):
            if path.resolve() == this_file:
                continue
            text = path.read_text(encoding="utf-8")
            if '".venv-analysis" / "Scripts" / "python.exe"' in text:
                hits.append(path.name)
        self.assertEqual(hits, [])


if __name__ == "__main__":
    unittest.main()
